version: 2

models:
    - name: fact_orders
      columns:
         - name: pedidos
           description: "Chave primária"
           tests:
              - unique
              - not_null

    - name: dim_customers
      columns:
         - name: customer_id
           description: "Chave primária"
           tests:
              - unique
              - not_null

    - name: dim_products
      columns:
         - name: product_id
           description: "Chave primária"
           tests:
              - unique
              - not_null
        
