version: 2

sources:
  - name: erp_northwind
    tables:
      - name: orders
      - name: customers
        columns:
          - name: customer_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null