version: 2

sources:
  - name: erp_northwind
    tables:
      - name: orders
      - name: customers
        columns:
          - name: customer_id
            description: Chave primária da tabela Clientes
            tests:
              - unique
              - not_null
      - name: products
        columns:
          - name: product_id
            description: Chave primária da tabela Produtos
      - name: order_details
        columns:
          - name: order_id
      - name: suppliers
        columns:
          - name: supplier_id
      - name: employees
        columns:
          - name: employee_id
      - name: date
        columns:
          - name: order_date